name: promoter
channels:
  - anaconda
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
  - conda-forge
dependencies:
  - pip
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _py-xgboost-mutex=2.0=cpu_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - biopython=1.83=py310h2372a71_0
  - blas=1.0=openblas
  - blinker=1.6.2=py310h06a4308_0
  - brotli-python=1.0.9=py310h6a678d5_7
  - bytecode=0.15.1=pyhd8ed1ab_0
  - bzip2=1.0.8=hd590300_5
  - ca-certificates=2024.7.2=h06a4308_0
  - chardet=4.0.0=py310h06a4308_1003
  - click=8.1.7=py310h06a4308_0
  - comm=0.2.1=pyhd8ed1ab_0
  - debugpy=1.8.0=py310hc6cd4ac_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - filelock=3.13.1=py310h06a4308_0
  - flask=3.0.3=py310h06a4308_0
  - flask_cors=3.0.10=pyhd3eb1b0_0
  - fsspec=2023.10.0=py310h06a4308_0
  - huggingface_hub=0.20.3=py310h06a4308_0
  - importlib-metadata=7.0.1=pyha770c72_0
  - importlib_metadata=7.0.1=hd8ed1ab_0
  - ipykernel=6.29.0=pyhd33586a_0
  - ipython=8.20.0=pyh707e725_0
  - itsdangerous=2.2.0=py310h06a4308_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_client=8.6.0=pyhd8ed1ab_0
  - jupyter_core=5.7.1=py310hff52083_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - levenshtein=0.25.0=py310hc6cd4ac_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_3
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=13.2.0=h807b86a_3
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.21=h043d6bf_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.44.2=h2797004_0
  - libstdcxx-ng=13.2.0=h7e041cc_3
  - libuuid=2.38.1=h0b41bf4_0
  - libxgboost=1.7.3=h6a678d5_0
  - libzlib=1.2.13=hd590300_5
  - lightgbm=4.3.0=py310h6a678d5_0
  - markupsafe=2.1.3=py310h5eee18b_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - ncurses=6.4=h59595ed_2
  - nest-asyncio=1.5.9=pyhd8ed1ab_0
  - numpy-base=1.26.0=py310h8a23956_0
  - openssl=3.2.1=hd590300_1
  - packaging=23.2=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - platformdirs=4.1.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - psutil=5.9.7=py310h2372a71_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py-xgboost=1.7.3=py310h06a4308_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.13=hd12c33a_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-levenshtein=0.25.0=pyhd8ed1ab_0
  - python_abi=3.10=4_cp310
  - pyyaml=6.0.1=py310h5eee18b_0
  - pyzmq=25.1.2=py310h795f18f_0
  - rapidfuzz=3.6.2=py310hc6cd4ac_0
  - readline=8.2=h8228510_1
  - regex=2023.10.3=py310h5eee18b_0
  - requests=2.31.0=py310h06a4308_1
  - safetensors=0.4.2=py310ha89cbab_0
  - setuptools=68.2.2=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tokenizers=0.15.1=py310h22610ee_0
  - tornado=6.3.3=py310h2372a71_1
  - traitlets=5.14.1=pyhd8ed1ab_0
  - transformers=4.37.2=py310h06a4308_0
  - typing_extensions=4.9.0=pyha770c72_0
  - urllib3=2.1.0=py310h06a4308_1
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - werkzeug=3.0.3=py310h06a4308_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h59595ed_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - pip:
      - arch==7.0.0
      - certifi==2023.11.17
      - charset-normalizer==3.3.2
      - cloudpickle==3.0.0
      - contourpy==1.2.0
      - cycler==0.12.1
      - et-xmlfile==1.1.0
      - fonttools==4.45.1
      - future==0.18.3
      - hyperopt==0.2.7
      - idna==3.6
      - jinja2==3.1.2
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - matplotlib==3.8.2
      - mpmath==1.3.0
      - networkx==3.2.1
      - numpy==1.26.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - openpyxl==3.1.2
      - pandas==2.1.3
      - patsy==0.5.6
      - pillow==10.1.0
      - pip==24.3.1
      - py4j==0.10.9.7
      - pyparsing==3.1.1
      - pytz==2023.3.post1
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - seaborn==0.13.0
      - statsmodels==0.14.2
      - sympy==1.12
      - threadpoolctl==3.2.0
      - torch==2.1.1
      - torchaudio==2.1.1
      - torchvision==0.16.1
      - tqdm==4.66.1
      - triton==2.1.0
      - typing-extensions==4.8.0
      - tzdata==2023.3
      - visualizer==0.0.1
